### ISSUE TITLE
functions missing required positional arguments

### ISSUE THREAD

**Issue by zbchern** [soorya19/sparsity-based-defenses#1]
Hi, it seems that some functions miss required positional arguments, e.g.,
in test_dense_cnn.py line 81, model.get_logits(x) misses 'reuse',
in test_dense_cnn.py line 86, x_fgsm = fgsm.generate(x, eps=eps, clip_min=0., clip_max=1.) misses 'phase'.
I am using python 3.6.3 and tensorflow 1.6.0.
I appreciate it very much if you can add the missing arguments.

**Comment by soorya19** [comment]
Hi, the code works fine on my end (using TensorFlow 1.6, Python 3.6). The arguments are not missing; they have default values defined in line 68 (```phase=False```, ```reuse=tf.AUTO_REUSE```).

Can you share your output? Thanks.
